/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectou3aalg.view;

import com.mycompany.proyectou3aalg.util.Ciudad;
import com.mycompany.proyectou3aalg.util.Grafo;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Elite
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());
    

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setLayout(new BorderLayout());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionalidad = new javax.swing.JMenu();
        subMenuRecorridos = new javax.swing.JMenu();
        btnrecorridoBFS = new javax.swing.JMenuItem();
        btnRecorridoDFS = new javax.swing.JMenuItem();
        btnMST = new javax.swing.JMenuItem();
        btnRutaMásCorta = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        btnTablaNA = new javax.swing.JMenuItem();
        btnReporteComplejidad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guanajuato Maps");

        menuFuncionalidad.setText("Funcionalidades");

        subMenuRecorridos.setText("Recorridos");

        btnrecorridoBFS.setText("BFS");
        subMenuRecorridos.add(btnrecorridoBFS);

        btnRecorridoDFS.setText("DFS");
        btnRecorridoDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorridoDFSActionPerformed(evt);
            }
        });
        subMenuRecorridos.add(btnRecorridoDFS);

        menuFuncionalidad.add(subMenuRecorridos);

        btnMST.setText("MST");
        menuFuncionalidad.add(btnMST);

        btnRutaMásCorta.setText("Ruta más corta");
        menuFuncionalidad.add(btnRutaMásCorta);

        jMenuBar1.add(menuFuncionalidad);

        menuOtros.setText("Otros");

        btnTablaNA.setText("Tabla Nodos-Aristas");
        menuOtros.add(btnTablaNA);

        btnReporteComplejidad.setText("Reporte de complejidad");
        btnReporteComplejidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteComplejidadActionPerformed(evt);
            }
        });
        menuOtros.add(btnReporteComplejidad);

        jMenuBar1.add(menuOtros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteComplejidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteComplejidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteComplejidadActionPerformed

    private void btnRecorridoDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorridoDFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecorridoDFSActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnMST;
    private javax.swing.JMenuItem btnRecorridoDFS;
    private javax.swing.JMenuItem btnReporteComplejidad;
    private javax.swing.JMenuItem btnRutaMásCorta;
    private javax.swing.JMenuItem btnTablaNA;
    private javax.swing.JMenuItem btnrecorridoBFS;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFuncionalidad;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenu subMenuRecorridos;
    // End of variables declaration//GEN-END:variables

    
    
    public Grafo inicializarCiudadesYGrafo(String[] nombres, int[][] matrizAristas){
       
        // Crea un nuevo grafo
        Grafo grafo = new Grafo();
        //Crea un arreglo de ciudades
        Ciudad[] ciudades = new Ciudad[30];
        //Ciclo que crea objetos ciudad, los añade al arreglo ciudades
        // y al grafo.
        for (int i = 0; i < nombres.length; i++) {
            ciudades[i] = new Ciudad(i, nombres[i]);
            grafo.agregarCiudad(ciudades[i]);

        }
        //Ciclo Matriz de Adyacencias
        for (int i = 0; i < 30; i++) { //recorre ciudades origen
            for (int j = i + 1; j < 30; j++) { // recorre ciudades destino
                if (matrizAristas[i][j] > 0) {
                    grafo.agregarArista(ciudades[i], ciudades[j], matrizAristas[i][j]);
                }
            }
        }

        return grafo;
        
    }
    
    
    
    //Genera posiciones para el Jframe que simulan la geografía del estado de Guanajuato
    public int[][] generarPosiciones(double [][] coordenadas){
        //Convertir coordenadas geograficas a pixeles
        int [][] posiciones = new int[coordenadas.length][2];
        double minLat = 20.0, maxLat = 21.5;
        double minLon = -102.0, maxLon = -100.3;

        for (int i = 0; i < coordenadas.length; i++) {
            double lat = coordenadas[i][0];
            double lon = coordenadas[i][1];
            int x = (int) ((lon - minLon) / (maxLon - minLon) * 1000);
            int y = (int) ((maxLat - lat) / (maxLat - minLat) * 700);
            posiciones[i][0] = x;
            posiciones[i][1] = y;
        }
        
        //Aplicar separación minima entre nodos 
        for (int i = 0; i < posiciones.length; i++) {
            for (int j = i + 1; j < posiciones.length; j++) {
                int dx = posiciones[i][0] - posiciones[j][0];
                int dy = posiciones[i][1] - posiciones[j][1];
                double distancia = Math.sqrt(dx * dx + dy * dy);
                if (distancia < 30) { // mínimo 30 píxeles
                    posiciones[j][0] += 20;
                    posiciones[j][1] += 20;
                }
            }
        }
        
        
        
        return posiciones;
    }
    
    
      



}
